package modelos;
// Generated 12-abr-2017 11:45:32 by Hibernate Tools 4.3.1



/**
 * Clientes generated by hbm2java
 */
public class Clientes extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private Integer idCliente;
     private String nickName;
     private String cif;
     private int cp;
     private String direccion;
     private String mail;
     private String razonSocial;
     private Integer telefono;

    public Clientes() {
    }

	
    public Clientes(String nickName, String cif, int cp, String direccion, String mail, String razonSocial) {
        this.nickName = nickName;
        this.cif = cif;
        this.cp = cp;
        this.direccion = direccion;
        this.mail = mail;
        this.razonSocial = razonSocial;
    }
    public Clientes(String nickName, String cif, int cp, String direccion, String mail, String razonSocial, Integer telefono) {
       this.nickName = nickName;
       this.cif = cif;
       this.cp = cp;
       this.direccion = direccion;
       this.mail = mail;
       this.razonSocial = razonSocial;
       this.telefono = telefono;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getCif() {
        return this.cif;
    }
    
    public void setCif(String cif) {
        this.cif = cif;
    }
    public int getCp() {
        return this.cp;
    }
    
    public void setCp(int cp) {
        this.cp = cp;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }




}


