package modelos;
// Generated 12-abr-2017 11:45:32 by Hibernate Tools 4.3.1



/**
 * Conceptos generated by hbm2java
 */
public class Conceptos extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private Integer idConcepto;
     private String nickName;
     private String descripcion;
     private String base;
     private String iva;
     private String nombreConcepto;
     private int numeroFactura;
     private int cantidad;

    public Conceptos() {
    }

	
    public Conceptos(String nickName, String base, String iva, String nombreConcepto, int numeroFactura, int cantidad) {
        this.nickName = nickName;
        this.base = base;
        this.iva = iva;
        this.nombreConcepto = nombreConcepto;
        this.numeroFactura = numeroFactura;
        this.cantidad = cantidad;
    }
    public Conceptos(String nickName, String descripcion, String base, String iva, String nombreConcepto, int numeroFactura, int cantidad) {
       this.nickName = nickName;
       this.descripcion = descripcion;
       this.base = base;
       this.iva = iva;
       this.nombreConcepto = nombreConcepto;
       this.numeroFactura = numeroFactura;
       this.cantidad = cantidad;
    }
   
    public Integer getIdConcepto() {
        return this.idConcepto;
    }
    
    public void setIdConcepto(Integer idConcepto) {
        this.idConcepto = idConcepto;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getBase() {
        return this.base;
    }
    
    public void setBase(String base) {
        this.base = base;
    }
    public String getIva() {
        return this.iva;
    }
    
    public void setIva(String iva) {
        this.iva = iva;
    }
    public String getNombreConcepto() {
        return this.nombreConcepto;
    }
    
    public void setNombreConcepto(String nombreConcepto) {
        this.nombreConcepto = nombreConcepto;
    }
    public int getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }




}


