package modelos;
// Generated 12-abr-2017 11:45:32 by Hibernate Tools 4.3.1



/**
 * Facturas generated by hbm2java
 */
public class Facturas extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private Integer idFactura;
     private String nickName;
     private int numeroFactura;
     private String fecha;
     private String fechaVencimiento;
     private String nombreCliente;

    public Facturas() {
    }

    public Facturas(String nickName, int numeroFactura, String fecha, String fechaVencimiento, String nombreCliente) {
       this.nickName = nickName;
       this.numeroFactura = numeroFactura;
       this.fecha = fecha;
       this.fechaVencimiento = fechaVencimiento;
       this.nombreCliente = nombreCliente;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public int getNumeroFactura() {
        return this.numeroFactura;
    }
    
    public void setNumeroFactura(int numeroFactura) {
        this.numeroFactura = numeroFactura;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(String fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }




}


