package modelos;
// Generated 12-abr-2017 11:45:32 by Hibernate Tools 4.3.1



/**
 * Presupuestos generated by hbm2java
 */
public class Presupuestos extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private Integer idPresupuesto;
     private String nickName;
     private String fecha;
     private String fechaVencimiento;
     private int estado;
     private String nombreCliente;
     private String numeroPresupuesto;

    public Presupuestos() {
    }

    public Presupuestos(String nickName, String fecha, String fechaVencimiento, int estado, String nombreCliente, String numeroPresupuesto) {
       this.nickName = nickName;
       this.fecha = fecha;
       this.fechaVencimiento = fechaVencimiento;
       this.estado = estado;
       this.nombreCliente = nombreCliente;
       this.numeroPresupuesto = numeroPresupuesto;
    }
   
    public Integer getIdPresupuesto() {
        return this.idPresupuesto;
    }
    
    public void setIdPresupuesto(Integer idPresupuesto) {
        this.idPresupuesto = idPresupuesto;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getFecha() {
        return this.fecha;
    }
    
    public void setFecha(String fecha) {
        this.fecha = fecha;
    }
    public String getFechaVencimiento() {
        return this.fechaVencimiento;
    }
    
    public void setFechaVencimiento(String fechaVencimiento) {
        this.fechaVencimiento = fechaVencimiento;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getNumeroPresupuesto() {
        return this.numeroPresupuesto;
    }
    
    public void setNumeroPresupuesto(String numeroPresupuesto) {
        this.numeroPresupuesto = numeroPresupuesto;
    }




}


