package modelos;
// Generated 12-abr-2017 11:45:32 by Hibernate Tools 4.3.1



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios extends org.apache.struts.action.ActionForm implements java.io.Serializable {


     private Integer idUsuario;
     private String nickName;
     private String password;
     private String nif;
     private String razonSocial;
     private String codigoPostal;
     private String direccion;
     private String telefono;
     private int roll;

    public Usuarios() {
    }

	
    public Usuarios(String nickName, String password) {
        this.nickName = nickName;
        this.password = password;
        this.roll = 0;
    }
    public Usuarios(String nickName, String password, String nif, String razonSocial, String codigoPostal, String direccion, String telefono, int roll) {
       this.nickName = nickName;
       this.password = password;
       this.nif = nif;
       this.razonSocial = razonSocial;
       this.codigoPostal = codigoPostal;
       this.direccion = direccion;
       this.telefono = telefono;
       this.roll = roll;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getNickName() {
        return this.nickName;
    }
    
    public void setNickName(String nickName) {
        this.nickName = nickName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getRoll() {
        return this.roll;
    }
    
    public void setRoll(int roll) {
        this.roll = roll;
    }




}


