package com.mycompany.poliformismohibernate.modelos;
// Generated 18-abr-2017 13:38:43 by Hibernate Tools 4.3.1

import com.mycompany.poliformismohibernate.HibernateUtil.HerramientasHibernate;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;




/**
 * Motos generated by hbm2java
 */
public class Motos extends Vehiculos implements java.io.Serializable {


     private Integer idVehiculo;
     private String cilindrada;
     private String color;
     private String numeroRuedas;
     private String esAutomatico;
     private String modelo;
     
     private List<Motos> lista;

    public List<Motos> getLista() {
        return lista;
    }
     

    public Motos() {
    }

    public Motos(String cilindrada, String color, String numeroRuedas, String esAutomatico, String modelo) {
       this.cilindrada = cilindrada;
       this.color = color;
       this.numeroRuedas = numeroRuedas;
       this.esAutomatico = esAutomatico;
       this.modelo = modelo;
    }
   
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getCilindrada() {
        return this.cilindrada;
    }
    
    public void setCilindrada(String cilindrada) {
        this.cilindrada = cilindrada;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getNumeroRuedas() {
        return this.numeroRuedas;
    }
    
    public void setNumeroRuedas(String numeroRuedas) {
        this.numeroRuedas = numeroRuedas;
    }
    public String getEsAutomatico() {
        return this.esAutomatico;
    }
    
    public void setEsAutomatico(String esAutomatico) {
        this.esAutomatico = esAutomatico;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    @Override
    public void cargar() {
        try {
            Session s = HerramientasHibernate.getSessionFactory().openSession();
            Transaction t = s.beginTransaction();
            Query q = s.createQuery("from Motos");
            this.lista = q.list();
            s.close();
            System.out.println("Motos cargadas");
        } catch (HibernateException e) {
            System.out.println("Error al actualizar la lista de motos "+e.getMessage());
        }
    }




}


