package com.mycompany.poliformismohibernate.modelos;
// Generated 18-abr-2017 13:38:43 by Hibernate Tools 4.3.1

import com.mycompany.poliformismohibernate.HibernateUtil.HerramientasHibernate;
import java.util.List;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;




/**
 * TodoTerreno generated by hbm2java
 */
public class TodoTerreno extends Vehiculos implements java.io.Serializable {


     private Integer idVehiculo;
     private String color;
     private String esAutomatico;
     private String numeroDeRuedas;
     private String es4x4;
     private String modelo;
     
     private List<TodoTerreno> lista;

    public List<TodoTerreno> getLista() {
        return lista;
    }
     
     

    public TodoTerreno() {
    }

    public TodoTerreno(String color, String esAutomatico, String numeroDeRuedas, String es4x4, String modelo) {
       this.color = color;
       this.esAutomatico = esAutomatico;
       this.numeroDeRuedas = numeroDeRuedas;
       this.es4x4 = es4x4;
       this.modelo = modelo;
    }
   
    public Integer getIdVehiculo() {
        return this.idVehiculo;
    }
    
    public void setIdVehiculo(Integer idVehiculo) {
        this.idVehiculo = idVehiculo;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public String getEsAutomatico() {
        return this.esAutomatico;
    }
    
    public void setEsAutomatico(String esAutomatico) {
        this.esAutomatico = esAutomatico;
    }
    public String getNumeroDeRuedas() {
        return this.numeroDeRuedas;
    }
    
    public void setNumeroDeRuedas(String numeroDeRuedas) {
        this.numeroDeRuedas = numeroDeRuedas;
    }
    public String getEs4x4() {
        return this.es4x4;
    }
    
    public void setEs4x4(String es4x4) {
        this.es4x4 = es4x4;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }

    @Override
    public void cargar() {
        try {
            Session s = HerramientasHibernate.getSessionFactory().openSession();
            Transaction t = s.beginTransaction();
            Query q = s.createQuery("from TodoTerreno");
            this.lista = q.list();
            s.close();
            System.out.println("Todo Terrenos cargados");
        } catch (HibernateException e) {
            System.out.println("Error al actualizar la lista de motos "+e.getMessage());
        }
    }




}


